name: time_converter
description: Support 12-hours time and 24-hours time conversion..
version: 0.1.0
homepage: https://github.com/zonble/time_converter

environment:
  sdk: '>=2.12.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
